#!/bin/bash
# helper script that jobs print head around corners of the printer.
# always going through center, to ensure all axies are moving all the time.
# this can be helper e.g. after linear rails lubrication.
#
set -eu -o pipefail

if [ $# -gt 2 ]
then
  echo "$(basename "$0") <N> <speed>" >&2
  exit 2
fi
n=${1:-10}
speed=${2-16000}
shift $#

cat <<EOF
g90 ; switch to absolute positioning
g0 x340 y10 z155 f$speed ; start position and set the speed
EOF

for((i=0; i<n; ++i))
do
  echo
  echo "; iteration $((i+1))/$n"
  cat <<EOF
; jog XY plane
g0 x10  y10
g0 x10  y340
g0 x340 y340
g0 x340 y10
; jog Z
g0 z10
g0 z300
g0 z155 ; center
EOF
done

cat <<EOF

; done
g0 x175 y175 z155 ; center
EOF
