#!/bin/bash
set -eu -o pipefail

user=klipperscreen
if ! id "$user" > /dev/null 2>&1
then
  adduser \
    --shell /bin/bash \
    --disabled-password \
    "$user" \
    < /dev/null
fi

systemctl daemon-reload
systemctl enable getty@tty1
systemctl start  getty@tty1
