#!/bin/bash
set -eu -o pipefail

user=klipperscreen
if ! id "$user" > /dev/null 2>&1
then
  adduser \
    --shell /bin/bash \
    --disabled-password \
    "$user" \
    < /dev/null
fi

# build images
(
  cd /opt/klipper
  echo "pulling docker images"
  docker-compose pull
  echo "building docker images"
  docker-compose build
)

echo "starting services"
systemctl daemon-reload
for s in \
  getty@tty1 \
  klipper-dc
do
  systemctl enable "$s"
  systemctl start  "$s"
done
