services:

  klipper:
    build: klipper
    read_only: true
    restart: always
    # TODO: run as non-root
    group_add:
      - dialout
      - tty
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - /dev/serial/by-id:/dev/serial/by-id:ro
      - /var/run/klipper/klipper:/mnt/run
      - /dev/pts/:/dev/pts/ # needed for link /mnt/run/klipper_host_mcu
      - ./klipper/data/config:/mnt/config
      - ./klipper/data/gcode:/mnt/data/gcodes:ro # TODO: R/W?
      - ./klipper/data/logs:/mnt/logs
    networks:
      - internal
    depends_on:
      - klipper_mcu

  klipper_mcu:
    build: klipper_mcu
    read_only: true
    restart: always
    # TODO: run as non-root
    group_add:
      - 995 # TODO: spi
      - tty
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/spidev0.0:/dev/spidev0.0
      - /dev/spidev0.1:/dev/spidev0.1
    volumes:
      - /var/run/klipper/klipper:/mnt/run # link to /dev/pts/<sth> will be here
      - /dev/pts/:/dev/pts/
    cap_add:
      - SYS_NICE # needed for RT scheduling
    networks: []

  moonraker:
    build: moonraker
    # TODO: cannot be read-onyl as is, since it does write to /tmp, etc...
    #read_only: true
    restart: always
    # TODO: run as non-root
    group_add:
      - video
    devices:
      - /dev/video0:/dev/video0
    volumes:
      - /var/run/klipper/moonraker:/mnt/run
      - /var/run/klipper/klipper:/mnt/klipper/run/
      - ./moonraker/data/config:/mnt/config
      - ./moonraker/data/logs:/mnt/logs
      - ./moonraker/data/data:/mnt/data
      - ./klipper/data/gcode:/mnt/data/gcodes
      - ./klipper/data/config:/opt/klipper/config:ro # does not seem to to configurable in moonraker
    depends_on:
      - klipper
    networks:
      - internal

  klipperscreen:
    build: klipperscreen
    read_only: true
    # TODO: run as non-root
    restart: always
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.Xauthority
    volumes:
      - /var/run/klipper/moonraker:/mnt/run
      - ./klipperscreen/data/config:/mnt/config
      - ./klipperscreen/data/logs:/mnt/logs
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime:ro
      # following 2 entries allow for OS shutdown / restart from touch screen
      - /run/dbus:/run/dbus
      - /run/systemd:/run/systemd
    depends_on:
      - moonraker
    networks:
      - internal

  fluidd:
    image: ghcr.io/fluidd-core/fluidd:v1.32.6
    restart: always
    networks:
      - internal

  cornercam:
    build: mjpeg_server
    user: "nobody:nogroup"
    read_only: true
    restart: always
    devices:
      - /dev/video0:/dev/video0
    group_add:
      - video
    networks:
      - internal

  # only nginx has an access to/trom the outside world - all other containers are cut off
  nginx:
    image: nginx:1.27
    # read_only: true # TODO: cannot be read-only atm, due to: [emerg] 1#1: mkdir() "/var/cache/nginx/client_temp" failed (30: Read-only file system)
    restart: always
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/pass:/etc/nginx/pass:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - moonraker
      - fluidd
      #- cornercam # not strictly needed - this is a secondary feature
    networks:
      - internal
      - external


networks:
  internal:
    driver: bridge
    internal: true
  external:
    driver: bridge
