services:

  klipper:
    build: klipper
    group_add:
      - dialout
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - /dev/serial/by-id:/dev/serial/by-id:ro
      - /var/run/klipper/klipper:/mnt/run
      - ./klipper/data/config:/mnt/config
      - ./klipper/data/gcode:/mnt/gcodes:ro
      - ./klipper/data/logs:/mnt/logs
