services:

  klipper:
    build: klipper
    # TODO: run as non-root
    group_add:
      - dialout
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - /dev/serial/by-id:/dev/serial/by-id:ro
      - /var/run/klipper/klipper:/mnt/run
      - ./klipper/data/config:/mnt/config
      - ./klipper/data/gcode:/mnt/data/gcodes:ro
      - ./klipper/data/logs:/mnt/logs

  moonraker:
    build: moonraker
    # TODO: run as non-root
    network_mode: host
    volumes:
      - /var/run/klipper/moonraker:/mnt/run
      - /var/run/klipper/klipper:/mnt/klipper/run/
      - ./moonraker/data/config:/mnt/config
      - ./moonraker/data/logs:/mnt/logs
      - ./moonraker/data/data:/mnt/data
      - ./klipper/data/config:/opt/klipper/config:ro # does not seem to to configurable in moonraker
    depends_on:
      - klipper

  klipperscreen:
    build: klipperscreen
    # TODO: run as non-root
    network_mode: host
    restart: always
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.Xauthority
    volumes:
      - /var/run/klipper/moonraker:/mnt/run
      - ./klipperscreen/data/config:/mnt/config
      - ./klipperscreen/data/logs:/mnt/logs
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime:ro
      # following 2 entries allow for OS shutdown / restart from touch screen
      - /run/dbus:/run/dbus
      - /run/systemd:/run/systemd
    depends_on:
      - moonraker

# TODO: add nginx for reverse proxy (HTTPS + basic-auth / mTLS)
